---
# handlers file for vector-role
- name: Start vector service
  become: true
  ansible.builtin.service:
    name: vector
    state: restarted
- name: Reload systemd
  ansible.builtin.systemd:
    name: vector
    state: reloaded